config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :deputies, only: [ :index, :show, :edit ]
  resources :events, only: [ :index, :show ]
  resources :parties, only: [ :index, :show ]
  resources :votes, only: [ :index, :show ]

  get "home/votes", to: "home#votes"
  get "home/links", to: "home#links"
  get "home/about", to: "home#about"
end

app/models/deputy.rb
class Deputy < ApplicationRecord
  belongs_to :party, optional: true
  has_many :deputy_expenses, dependent: :destroy
  has_many :deputy_external_mandates, dependent: :destroy
  has_many :deputy_fronts, dependent: :destroy
  has_many :deputy_histories, dependent: :destroy
  has_many :deputy_ocupations, dependent: :destroy
  has_many :deputy_speeches, dependent: :destroy
  has_many :deputy_votes, dependent: :destroy
  has_many :event_deputies, dependent: :destroy
  has_many :professions, dependent: :destroy
  has_many :events, through: :event_deputies
  has_many :fronts, through: :deputy_fronts
  has_many :votes, through: :deputy_votes
  validates :external_id, uniqueness: true
end

app/controllers/deputies_controller.rb
class DeputiesController < ApplicationController
  before_action :result, only: %i[ show ]
  SUBJECT = "deputados".freeze
  CACHE_KEY = "deputies_all".freeze
  EXPIRING_TIME = 5.days
  DROP_LIST = [
    "deputado",
    "despesas",
    "discursos",
    "eventos",
    "frentes",
    "profissoes",
    "lideres",
    "mandatosExternos",
    "historico",
    "mesa",
    "orgaos",
    "ocupacoes"
  ].freeze
  def index
    @deputies_research_subject = DROP_LIST
    @deputy_selected_id = params[:deputy_id]
    @deputy_selected_name = params[:deputy_name]
    @deputies_list = Service::FetchList.call(SUBJECT, CACHE_KEY, EXPIRING_TIME)["dados"]
  end
  def show
    @result_page_data
  end
  def edit
    @deputies_research_subject = DROP_LIST
    @deputy_selected_id = params[:id]
    @deputy_selected_name = params[:name]
    @deputy_selected_research = params[:options]
  end

  private

  def result
    @date_selector = [
      "deputado",
      "despesas",
      "frentes",
      "historico",
      "mandatosExternos",
      "ocupacoes",
      "profissoes",
      "lideres",
      "codSituacao",
      "situacoesDeputado"
    ]
    deputy_id = params[:id]
    deputy_name = params[:name]
    research = (params[:research] || params[:options])

    @deputies_research = { name: deputy_name, id: deputy_id, options: research }

    research_filter_func(ClientDeputiesResearch, @deputies_research)
  end
end

app/helpers/deputy_helper.rb
module DeputyHelper
end

app/views/deputies/edit.html.erb
<%= form_with url: deputy_path(id: @deputy_selected_id, params: { name: @deputy_selected_name, research: @deputy_selected_research }), class: 'form', method: :get do |f| %>
  <%= f.label :name, 'Nome do deputado' %>
  <%= f.text_field :name, value: (@deputy_selected_name || nil), disabled: true %>
  <%= f.hidden_field :name, value: @deputy_selected_name %>
  <%= f.label :id, 'ID do deputado' %>
  <%= f.text_field :id, value: (@deputy_selected_id || nil), disabled: true %>
  <%= f.hidden_field :id, value: @deputy_selected_id %>
  <%= f.label :options, 'Assunto' %>
  <%= f.text_field :options, value: (@deputy_selected_research || nil), disabled: true %>
  <%= f.hidden_field :options, value: @deputy_selected_research %>
  <%= f.label :initial_date, 'Data inicial' %>
  <%= f.text_field :initial_date, type: 'date' %>
  <%= f.label :final_date, 'Data final' %>
  <%= f.text_field :final_date, type: 'date' %>
  <%= f.submit 'Buscar' %>
<% end %>

app/views/deputies/index.html.erb
<div>
  <%= turbo_frame_tag "deputies_form" do %>
    <%= render partial: "deputies/partials/deputies_form" %>
  <% end %>
  <% @deputies_list.map do |deputy| %>
    <p><%= link_to deputy["nome"], deputies_path(id: deputy["id"], params: { deputy_name: deputy["nome"], deputy_id: deputy["id"] }), method: :post, data: { turbo_frame: "deputies_form"} %> - <%= deputy["siglaPartido"] %></p>
  <% end %>
</div>

app/views/deputies/show.html.erb
<turbo-frame id="deputies_form">
  <% if @result_page_data["dados"].is_a?(Hash) %>
    <div>
      <table border="1">
        <thead>
          <tr>
            <th>Chave</th>
            <th>Informação</th>
          </tr>
        </thead>
        <tbody>
          <% @result_page_data["dados"].each do |key, value| %>
            <%= value_identifier(key, value) %>
          <% end %>
        </tbody>
      </table>
      <p>v1</p>
    </div>
  <% elsif @result_page_data["dados"].is_a?(Array) && @result_page_data["dados"].empty? %>
    <div>
      <p><strong>Nome:</strong> <%= @view_research_render %></p>
      <p><strong>Assunto:</strong>
        <%= @result_page_data["dados"].nil? || @result_page_data["dados"].empty? ? "Não encontrado" : @result_page_data["dados"] %>
      </p>
      <% if @result_page_data["links"].present? %>
        <p><strong>Links relacionados:</strong></p>
        <ul>
          <% @result_page_data["links"].each do |link| %>
            <li>
              <%= link_to link["rel"].capitalize, link["href"], target: "_blank", rel: "noopener" %>
            </li>
          <% end %>
        </ul>
      <% end %>
      <p>v2</p>
    </div>
  <% elsif @result_page_data["dados"].is_a?(Array) && !@result_page_data["dados"].empty? %>
    <% sorted_data = (@result_page_data["dados"]).sort_by do |item| 
        [
          item["mes"] ? -item["mes"].to_i : Float::INFINITY,
          -item["id"].to_i
        ]
      end %>
    <div>
      <p>Nome: <%= @deputies_research[:name] %> </p>
      <table border="1">
        <thead>
          <tr>
            <% sorted_data.first.keys.each do |key| %>
              <th><%= content_tag(:strong, key.capitalize) %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% sorted_data.each do |item| %>
            <tr>
              <% item.each_value do |value| %>
                <td><%= render_hash_value(value) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p>v3</p>
    </div>
  <% else %>
    <div>
      <p><%= @result_page_data || "<strong>Não foi possível encontrar</strong>" %></p>
      <p>v4</p>
    </div>
  <% end %>
</turbo-frame>