config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :deputies, only: [ :index, :show, :edit ]
  resources :events, only: [ :index, :show ]
  resources :parties, only: [ :index, :show ]
  resources :votes, only: [ :index, :show ]

  get "home/votes", to: "home#votes"
  get "home/links", to: "home#links"
  get "home/about", to: "home#about"
end

app/models/vote.rb
class Vote < ApplicationRecord
  has_many :deputies, through: :deputy_votes
  has_many :deputy_votes
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :result, only: %i[ show ]
  SUBJECT = "votacoes".freeze
  CACHE_KEY = "votes_all".freeze
  EXPIRING_TIME = 5.days
  DROP_LIST = [
    "votacoes",
    "orientacoes",
    "votos"
  ].freeze
  def index
    @vote_option_subject = DROP_LIST
    @vote_selected_id = params[:vote_id]
    if (params[:initial_date] || params[:final_date]).present?
      @initial_date = params[:initial_date] || nil
      @final_date = params[:final_date] || nil
      @votes_list = Service::FetchList.by_date(SUBJECT, CACHE_KEY, EXPIRING_TIME, @initial_date, @final_date)["dados"]
      if @votes_list.nil?
        @votes_list = Service::FetchList.call(SUBJECT, CACHE_KEY, EXPIRING_TIME)["dados"]
        if @votes_list.nil?
          @votes_list = { dados: [ { id: "1" }, { descricao: "Não foi possível encontrar" } ] }.to_json
        end
      end
    else
      @votes_list = Service::FetchList.call(SUBJECT, CACHE_KEY, EXPIRING_TIME)["dados"]
    end
  end
  def show
    @result_page_data
  end
  def date_select
    @vote_selected_id = params[:vote_id]
    @vote_selected_option = params[:options]
  end

  private

  def result
    @date_selector = DROP_LIST
    vote_id = params[:vote_id]
    options = params[:vote_options]

    @votes_research = { id: vote_id, options: options }

    research_filter_func(ClientVotesResearch, @votes_research)
  end
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/votes/partials/_date_select.html.erb
<turbo-frame id="date_form">
  <spam>
    <%= form_with url: votes_path, class: 'form', method: :get, data: { turbo_frame: "votes_list" } do |f| %>
      <%= f.label :initial_date, 'Data inicial' %>
      <%= f.text_field :initial_date, type: 'date' %>
      <%= f.label :final_date, 'Data final' %>
      <%= f.text_field :final_date, type: 'date' %>
      <%= f.submit 'Filtrar' %>
    <% end %>
  </spam>
</turbo-frame>

app/views/votes/partials/_votes_form.html.erb
<turbo-frame id="votes_form">
  <span>
    <%= form_with url: vote_path(id: @vote_selected_id || 1), class: 'form', method: :get, data: { turbo: "false" } do |f| %>
      <%= f.label :vote_id, 'ID da votação' %>
      <%= f.text_field :vote_id, value: (@vote_selected_id || nil), disabled: true %>
      <%= f.hidden_field :vote_id, value: @vote_selected_id %>
      <%= f.label :vote_options, 'Opções' %>
      <%= select_tag 'vote_options', options_for_select(@vote_option_subject.sort, @vote_option_subject.first) %>
      <%= f.submit 'Buscar' %>
    <% end %>
  </span>
</turbo-frame>