config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :deputies, only: [ :index, :show, :edit ]
  resources :events, only: [ :index, :show ]
  resources :parties, only: [ :index, :show ]
  resources :votes, only: [ :index, :show ]

  get "home/votes", to: "home#votes"
  get "home/links", to: "home#links"
  get "home/about", to: "home#about"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div>
  <h2>Sobre o Projeto Xandaum</h2>
  <p>
    O <strong>Projeto Xandaum</strong> é uma interface intuitiva e acessível desenvolvida para facilitar a consulta e a interação com os dados disponíveis na plataforma da <strong>Câmara dos Deputados do Brasil</strong>.<br>
    Essa ferramenta utiliza a API de Dados Abertos da Câmara (<a href="https://dadosabertos.camara.leg.br/api/v2/" target="_blank">https://dadosabertos.camara.leg.br/api/v2/</a>) para permitir que interessados acompanhem a atividade parlamentar de maneira simples e eficiente.
  </p>
</p>
<h2>Objetivos do Projeto</h2>
<ul>
  <li><strong>Facilitar o acesso à informação:</strong> Simplificar o processo de consulta a dados públicos, como informações sobre deputados, votações e eventos.</li>
  <li><strong>Promover a transparência:</strong> Contribuir para a transparência das atividades legislativas, tornando os dados mais compreensíveis e acessíveis a todos.</li>
  <li><strong>Empoderar cidadãos:</strong> Oferecer uma ferramenta que estimule a participação cidadã na política brasileira.</li>
</ul>
<h2>Funcionalidade Principal</h2>
<ul>
  <li><strong>Busca Detalhada:</strong> Permite localizar dados específicos de maneira rápida e eficiente utilizando de uma interface.</li>
</ul>
<h2>Tecnologias Utilizadas</h2>
<ul>
  <li><strong>Ruby on Rails:</strong> Framework principal para desenvolvimento da aplicação.</li>
  <li><strong>API de Dados Abertos da Câmara:</strong> Fonte de informações legislativas e parlamentares.</li>
</ul>
<h2>Como Usar o Projeto Xandaum</h2>
<ol>
  <li><strong>Acesse a plataforma:</strong> Navegue pelas seções da interface.</li>
  <li><strong>Pesquise informações:</strong> Utilize os campos de busca para encontrar deputados, eventos, votações e partidos.</li>
  <li><strong>Explore os dados:</strong> Visualize informações detalhadas sobre a atividade parlamentar.</li>
</ol>
</p>
</div>

app/views/home/events.erb
<div>
  <h3>Lista de eventos</h3>
  <% @events_list.each do |event| %>
    <p><%= event["id"] %> 
    - <strong>NOME:</strong> <%= event.dig("orgaos", 0, "apelido") %> 
    | <strong>INÍCIO:</strong> <%= event["dataHoraInicio"] %> 
    | <strong>FIM:</strong> <%= event["dataHoraFim"] %> 
    | <strong>SITUAÇÃO:</strong> <%= event["situacao"] %></p>
  <% end %>
</div>

app/views/home/index.html.erb
<div>
  <nav>
  </nav>
  <ul>
    <li>
      <h3><%= link_to 'Deputados', deputies_path %></h3>
      <p>- Selecione o deputado desejado clicando em seu nome<br>
        - Selecione o assunto através do menu<br>
        - Clique em buscar</p>
    </li>
    <li>
      <h3><%= link_to 'Eventos', events_path %></h3>
      <p>- Selecione o evento desejado clicando em seu ID ou intervalo entre as datas através dos calendários<br>
        - Selecione a opção desejada através do menu<br>
        - Clique em buscar
      </p>
    </li>
    <li>
      <h3><%= link_to 'Partidos', parties_path %></h3>
      <p>- Selecione o partido desejado clicando em sua sigla</p>
    </li>
    <li>
      <h3><%= link_to 'Votações', votes_path %></h3>
      <p>- Selecione a votação desejada clicando em seu ID ou intervalo entre as datas através dos calendários<br>
        - Selecione a opção desejada através do menu<br>
        - Clique em buscar
      </p>
    </li>
  </ul>
</div>

app/views/home/links.html.erb
<div>
  <a href="mailto:projeto.xandaum@gmail.com?">projeto.xandaum@gmail.com</a>
</div>