config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :deputies, only: [ :index, :show, :edit ]
  resources :events, only: [ :index, :show ]
  resources :parties, only: [ :index, :show ]
  resources :votes, only: [ :index, :show ]

  get "home/votes", to: "home#votes"
  get "home/links", to: "home#links"
  get "home/about", to: "home#about"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :deputies, through: :event_deputies
  has_many :event_deputies
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :result, only: %i[ show ]
  SUBJECT = "eventos".freeze
  CACHE_KEY = "events_all".freeze
  EXPIRING_TIME = 5.days
  DROP_LIST = [
    "eventos",
    "deputados",
    "orgaos",
    "pauta",
    "votacoes",
    "situacoesEvento",
    "tiposEvento",
    "codSituacaoEvento",
    "codTipoEvento"
  ].freeze
  def index
    @event_option_subject = [
      "eventos",
      "deputados",
      "orgaos",
      "pauta",
      "votacoes",
      "situacoesEvento"
      # "tiposEvento"
    ]
    @event_selected_id = params[:event_id]

    if (params[:initial_date] || params[:final_date]).present?
      @initial_date = params[:initial_date] || nil
      @final_date = params[:final_date] || nil
      @events_list = if Service::FetchList.by_date(SUBJECT, CACHE_KEY, EXPIRING_TIME, @initial_date, @final_date)["dados"].nil?
        # TODO: Notice - "Não foi possível encontrar"
        Service::FetchList.call(SUBJECT, CACHE_KEY, EXPIRING_TIME)["dados"]
      else
        Service::FetchList.by_date(SUBJECT, CACHE_KEY, EXPIRING_TIME, @initial_date, @final_date)["dados"]
      end
    else
      @events_list = Service::FetchList.call(SUBJECT, CACHE_KEY, EXPIRING_TIME)["dados"]
    end
  end
  def show
    @result_page_data
  end

  def edit
    @event_option_subject = DROP_LIST
    @event_selected_id = params[:event_id]
    @event_selected_option = params[:options]
  end

  private

  def result
    @date_selector = DROP_LIST
    event_id = params[:event_id]
    options = params[:options]

    @event_research = { id: event_id, options: options }

    research_filter_func(ClientEventsResearch, @event_research)
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/partials/_date_select.html.erb
<turbo-frame id="date_form">
  <spam>
    <%= form_with url: events_path, class: 'form', method: :get, data: { turbo_frame: "events_list" } do |f| %>
      <%= f.label :initial_date, 'Data inicial' %>
      <%= f.text_field :initial_date, type: 'date' %>
      <%= f.label :final_date, 'Data final' %>
      <%= f.text_field :final_date, type: 'date' %>
      <%= f.submit 'Filtrar' %>
    <% end %>
  </spam>
</turbo-frame>

app/views/events/partials/_events_form.html.erb
<turbo-frame id="events_form">
  <span>
    <%= form_with url: event_path(id: @event_selected_id || 1), class: 'form', method: :get, data: { turbo: "false" } do |f| %>
      <%= f.label :event_id, 'ID do evento' %>
      <%= f.text_field :event_id, value: (@event_selected_id || nil), disabled: true %>
      <%= f.hidden_field :event_id, value: @event_selected_id %>
      <%= f.label :options, 'Opções' %>
      <%= select_tag 'options', options_for_select(@event_option_subject.sort, @event_option_subject.first) %>
      <%= f.submit 'Buscar' %>
    <% end %>
  </span>
</turbo-frame>